# CMake generated Testfile for 
# Source directory: /workspace
# Build directory: /workspace/build_test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_qcap2_buffer "/workspace/build_test/test_qcap2_buffer")
set_tests_properties(test_qcap2_buffer PROPERTIES  _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;105;add_test;/workspace/CMakeLists.txt;213;qcap2_add_test;/workspace/CMakeLists.txt;0;")
add_test(test_qcap2_formats "/workspace/build_test/test_qcap2_formats")
set_tests_properties(test_qcap2_formats PROPERTIES  _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;105;add_test;/workspace/CMakeLists.txt;214;qcap2_add_test;/workspace/CMakeLists.txt;0;")
add_test(test_qcap2_utils "/workspace/build_test/test_qcap2_utils")
set_tests_properties(test_qcap2_utils PROPERTIES  _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;105;add_test;/workspace/CMakeLists.txt;215;qcap2_add_test;/workspace/CMakeLists.txt;0;")
add_test(test_qcap2_sync "/workspace/build_test/test_qcap2_sync")
set_tests_properties(test_qcap2_sync PROPERTIES  _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;105;add_test;/workspace/CMakeLists.txt;216;qcap2_add_test;/workspace/CMakeLists.txt;0;")
add_test(test_qcap2_audio_sink "/workspace/build_test/test_qcap2_audio_sink")
set_tests_properties(test_qcap2_audio_sink PROPERTIES  _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;105;add_test;/workspace/CMakeLists.txt;217;qcap2_add_test;/workspace/CMakeLists.txt;0;")
add_test(test_qcap2_video_sink "/workspace/build_test/test_qcap2_video_sink")
set_tests_properties(test_qcap2_video_sink PROPERTIES  _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;105;add_test;/workspace/CMakeLists.txt;218;qcap2_add_test;/workspace/CMakeLists.txt;0;")
add_test(test_qcap2_demuxer "/workspace/build_test/test_qcap2_demuxer")
set_tests_properties(test_qcap2_demuxer PROPERTIES  _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;105;add_test;/workspace/CMakeLists.txt;221;qcap2_add_test;/workspace/CMakeLists.txt;0;")
add_test(test_qcap2_demuxer_rtsp "/workspace/build_test/test_qcap2_demuxer_rtsp")
set_tests_properties(test_qcap2_demuxer_rtsp PROPERTIES  _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;105;add_test;/workspace/CMakeLists.txt;222;qcap2_add_test;/workspace/CMakeLists.txt;0;")
add_test(test_qcap2_demuxer_mock "/workspace/build_test/test_qcap2_demuxer_mock")
set_tests_properties(test_qcap2_demuxer_mock PROPERTIES  _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;105;add_test;/workspace/CMakeLists.txt;223;qcap2_add_test;/workspace/CMakeLists.txt;0;")
add_test(test_qcap2_muxer "/workspace/build_test/test_qcap2_muxer")
set_tests_properties(test_qcap2_muxer PROPERTIES  _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;105;add_test;/workspace/CMakeLists.txt;227;qcap2_add_test;/workspace/CMakeLists.txt;0;")
add_test(test_qcap2_muxer_rtsp "/workspace/build_test/test_qcap2_muxer_rtsp")
set_tests_properties(test_qcap2_muxer_rtsp PROPERTIES  _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;105;add_test;/workspace/CMakeLists.txt;228;qcap2_add_test;/workspace/CMakeLists.txt;0;")
add_test(test_qcap2_demux_mux "/workspace/build_test/test_qcap2_demux_mux")
set_tests_properties(test_qcap2_demux_mux PROPERTIES  _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;105;add_test;/workspace/CMakeLists.txt;232;qcap2_add_test;/workspace/CMakeLists.txt;0;")
add_test(test_qcap2_sdp "/workspace/build_test/test_qcap2_sdp")
set_tests_properties(test_qcap2_sdp PROPERTIES  _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;105;add_test;/workspace/CMakeLists.txt;233;qcap2_add_test;/workspace/CMakeLists.txt;0;")
add_test(test_qcap2_processing "/workspace/build_test/test_qcap2_processing")
set_tests_properties(test_qcap2_processing PROPERTIES  _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;105;add_test;/workspace/CMakeLists.txt;237;qcap2_add_test;/workspace/CMakeLists.txt;0;")
add_test(test_qcap2_graphics "/workspace/build_test/test_qcap2_graphics")
set_tests_properties(test_qcap2_graphics PROPERTIES  _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;105;add_test;/workspace/CMakeLists.txt;241;qcap2_add_test;/workspace/CMakeLists.txt;0;")
